### ISSUE TITLE
Fedora 35 Silverblue unable to install dangerzone

### ISSUE THREAD

**Issue by FredBts** [freedomofpress/dangerzone#151]
I am not able to install dangerzone within a Fedora Silverblue container:

Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.3.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 928, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for dangerzone

**Comment by deeplow** [comment]
Fedora Silverblue isn't official supported at the moment, unfortunately. So I'll close this. If you managed to figure out how to install Dangerzone there, feel free to share here.
