### ISSUE TITLE
Build fails for debian 12: No module named 'shiboken2.shiboken2'

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#172]
Dangerzone on Debian 12 (a.k.a. bookworm) is failing to build the .deb.

See the [failure log](https://app.circleci.com/pipelines/github/freedomofpress/dangerzone/289/workflows/280fc16b-f69c-4987-938d-8452533c48c4/jobs/818).

```log
I: pybuild base:239: cd /root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build; python3.9 -m unittest discover -v 
PySide2/__init__.py: Unable to import shiboken2 from /root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build, /root/project/deb_dist/dangerzone-0.3.1/debian/python3-dangerzone/usr/lib/python3.9/dist-packages, /root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build, /usr/lib/python39.zip, /usr/lib/python3.9, /usr/lib/python3.9/lib-dynload, /usr/local/lib/python3.9/dist-packages, /usr/lib/python3/dist-packages
dangerzone (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: dangerzone (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: dangerzone
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build/dangerzone/__init__.py", line 16, in <module>
    from .gui import gui_main as main
  File "/root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build/dangerzone/gui/__init__.py", line 7, in <module>
    from PySide2 import QtCore, QtWidgets
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/usr/lib/python3/dist-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/usr/lib/python3/dist-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
E: pybuild pybuild:369: test: plugin distutils failed with: exit code=1: cd /root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.9_dangerzone/build; python3.9 -m unittest discover -v 
I: pybuild base:239: cd /root/project/deb_dist/dangerzone-0.3.1/.pybuild/cpython3_3.10_dangerzone/build; python3.10 -m unittest discover -v
```

**Comment by deeplow** [comment]
Somehow in Debian 12 it is detecting "gui" as test. Furthermore, this is does not happen when python10 is used instead of python3.9.

**Comment by deeplow** [comment]
This sounds like that could be the problem. Thanks for finding it @legoktm. I'll look in distro's bug trackers next time.

Then I guess this is an upstream bug and with time it should be fixed. Debian 12 won't be out for quite a while, so we might was well wait.

**Comment by deeplow** [comment]
I'm not sure it's related but I've come across another issue with the `shiboken2` package while running `poetry install` on an m1 macbook:

![error_shiboken](https://user-images.githubusercontent.com/47065258/180788493-8a725a44-1ead-4d32-b6cc-5d022cdb9572.png)

**Comment by deeplow** [comment]
A similar thing has happened on windows a while ago: https://bugreports.qt.io/browse/PYSIDE-1002
