### ISSUE TITLE
Broken on macOS, cannot pull the image correctly apparently

### ISSUE THREAD

**Issue by artemislena** [freedomofpress/dangerzone#176]
L: Uh, so we tried installing and using Dangerzone recently, and it just doesn't work, looks like it doesn't pull the image. Might be related to https://github.com/freedomofpress/dangerzone/issues/152 ? When we try to convert a document, it says `Invalid JSON returned from container:` at the top, and at the bottom `Unable to find image 'dangerzone.rocks/dangerzone:latest' locally` at first, but only for such a short moment you can't read it unless you do a screen recording, then `See docker run --help`.

**Comment by deeplow** [comment]
Did you install [docker desktop](https://www.docker.com/products/docker-desktop)? After installed, it must be opened before running Dangerzone.

**Comment by artemislena** [comment]
Yeah, it's installed and running, we wouldn't even have gotten that far without that, as it did output an error message that Docker Desktop wasn't installed before we did that.

**Comment by deeplow** [comment]
OK. I'm in the process of getting access to a mac computer for testing dangerzone. Once I have, I'll try to reproduce this. Can you tell me the macOS version and if it's an Intel mac or one of the newer runs running an M1 chip?

**Comment by artemislena** [comment]
M1 chip. Don't even know whether it's Mac-specific, though.

**Comment by akierig** [comment]
it's failing on an Ubuntu ARM VM as well, can't connect to the remote

from stdout:

```
> /usr/bin/podman run --network none -v /home/akierig/52bcfb37.pdf:/tmp/input_file -v /home/akierig/etc/dangerzone/tmp/tmp3ng83hk5/pixels:/dangerzone dangerzone.rocks/dangerzone /usr/bin/python3 /usr/local/bin/dangerzone.py document-to-pixels

Invalid JSON returned from container: Trying to pull dangerzone.rocks/dangerzone:latest...
```

**Comment by deeplow** [comment]
> When we try to convert a document, it says `Invalid JSON returned from container:` at the top, and at the bottom `Unable to find image 'dangerzone.rocks/dangerzone:latest' locally` at first, but only for such a short moment you can't read it unless you do a screen recording, then `See docker run --help`.

@artemislena the image should have been included in the download already. Weird.

With this information alone, I am not seeing where the issue may be. Can you help me get some more information about the issue by opening it in the terminal and copying here all error messages?
  * Can you open the `Terminal` application and run Dangerzone from there? Typing there the command `open -a Dangerzone` should do it.
  * After the application starts, choose a document and convert it
  * Then on the terminal copy here any errors that it showed at the bottom.

**Comment by deeplow** [comment]
> it's failing for me as well, it cannot pull from the remote. Built from source on a Ubuntu 22.04 VM to a DEB and then installed with `dpkg`.

This seems to be a different issue. It shouldn't pull from remote, since [there is nowhere to pull from](https://github.com/freedomofpress/dangerzone/issues/154). So you must have the image locally. Did you follow all the steps from [BUILD.md](https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md) file? Specifically, running the part that states:

> 
> Build the latest container:
> 
> ```sh
> ./install/linux/build-image.sh
> ```

**Comment by artemislena** [comment]
@deeplow Figured it out. We installed Dangerzone via Homebrew, which we run as a separate user for security reasons (i.e. so other apps can't install Homebrew apps without a password), and uh, basically we got
```
artemis@ArtemisBook ~ % /Applications/Dangerzone.app/Contents/MacOS/dangerzone
Installing Dangerzone container image...
Traceback (most recent call last):
  File "dangerzone/gui/main_window.py", line 98, in run
  File "dangerzone/global_common.py", line 440, in install_container
  File "gzip.py", line 58, in open
  File "gzip.py", line 173, in __init__
PermissionError: [Errno 13] Permission denied: '/Applications/Dangerzone.app/Contents/Resources/share/container.tar.gz'
```

Now, this is because for some reason, the container image (at `/Applications/Dangerzone.app/Contents/Resources/share/container.tar.gz`) doesn't have global read permissions, i.e. running `sudo chmod 644 /Applications/Dangerzone.app/Contents/Resources/share/container.tar.gz` would fix it, though I guess that change would be overwritten next time we uhm, upgrade Dangerzone again via Homebrew.

**Comment by deeplow** [comment]
Ah, I see. Thanks for figuring it out. I thought it was weird that I had not been able to reproduce this in a similar setup. But this explains it. 

Not sure giving 644 permissions to it would have any meaningful implications. If I may ask, why not just installing it via regular .dmg download? Is it because that way it lacks an updater?

**Comment by artemislena** [comment]
Well, security-wise, it probably wouldn't, because uh, the container image certainly isn't secret data, and after all it doesn't give write permissions or anything to others. Other files also have 644 rather than 600, which is, uhm, interesting, I guess.
Yeah, an updater is one thing, but Brew also has Casks of apps that *have* an integrated updater (in which case Brew won't upgrade it unless you add `--greedy` to `brew upgrade`); another reason some people use it is that it can be a lot faster to run a single `brew install foobar` than downloading Foobar, opening the DMG, agreeing to a license, dragging it into Applications and so on.

**Comment by almet** [comment]
Closing this as it doesn't seem to be related to the way we release Dangerzone, but more to the way it was specifically installed in this case.

Feel free to reopen if you think we should do something about it.
