### ISSUE TITLE
Inform the user when original files are in read-only dir

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#261]
It could be that the user selected files from a read-only directory.

## Behavior in Dangerzone v0.3.2
The user adds the file and starts the conversion without a problem. 

![allgood](https://user-images.githubusercontent.com/47065258/203773437-67863ae1-80cf-46fe-92a8-110c70b245fe.png)

However, in the debug log we observe an error:

```
[...]

[INFO] 100% Safe PDF created
Traceback (most recent call last):
  File "/usr/lib64/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/home/user/.config/dangerzone/tmp/tmp8a2109ew/safe/safe-output-compressed.pdf' -> '/home/user/dangerzone/tests/test_docs/sample-safe.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dangerzone/dangerzone/gui/main_window.py", line 518, in run
    if convert(
  File "/home/user/dangerzone/dangerzone/container.py", line 154, in convert
    shutil.move(container_output_filename, output_filename)
  File "/usr/lib64/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib64/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/user/dangerzone/tests/test_docs/sample-safe.pdf'
```

## Behavior in Dangerzone v0.4.0 (unreleased)

![dz-unaccounted-for](https://user-images.githubusercontent.com/47065258/203772732-d15acf61-fba9-483f-92fb-560bfbc0948a.png)

  - **Move original documents to 'unsafe' directory...**  will be disabled
    Since that directory cannot be created. Already implemented in https://github.com/freedomofpress/dangerzone/pull/255
  - **Save safe PDFs to...** won't work in the dir selected by default
    The default directory 

## Possible solution

Prevent the user from starting the conversion until they change the output directory via the <kbd>Choose</kbd> button. Perhaps mimic the behavior of setting the safe file extension to something other than `.pdf` -- where it shows a red warning that it must end in PDF and the "convert" button is disabled until that is fixed.

**Comment by apyrgio** [comment]
I was thinking about the same thing as well, I agree.

**Comment by apyrgio** [comment]
A user has recently stumbled on this error in a Windows system. In their case, the error log is the following:

```
\Users\dz\AppData\Local\pypoetry\Cache\virtualenvs\dangerzone-DU-xYaP2-py3.13\Lib\site-packages\pymupdf\mupdf.py", line 56040, in pdf_save_document
[pymupdf.mupdf.FzErrorSystem](http://pymupdf.mupdf.fzerrorsystem/): code=2: cannot open file <file>
```

Even though it says "cannot open file", the conversion does happen. At the very end of the conversion though, when Dangerzone attempts to save the safe PDF, this error gets triggered.

Oh, and I just remembered I've stumbled on the same issue, when sanitizing documents in a read-only Veracrypt container.

---

A workaround in this case is to select as an output directory a different folder that you have write access to, instead of moving original files to the `unsafe/` directory:

<img width="547" height="99" alt="Image" src="https://github.com/user-attachments/assets/8fd795c4-690d-4d42-9117-12eb6cc7f375" />
