### ISSUE TITLE
Github CI Runners are Running Out of Space

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#489]
Our dangerzone installation runners are failing on https://github.com/freedomofpress/dangerzone/pull/460, due to lack of space.

<details><summary>After installing the testing podman container, we have 3.3G</summary>

```bash
runner@fv-az1233-442:~/work/dangerzone/dangerzone$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   80G  3.3G  97% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   68K  694M   1% /run/user/1001
```
</details>

<details><summary>Within the container this is what we see the following </summary>

```
$ ./dev_scripts/env.py  --distro debian --version trixie run df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          84G   80G  3.3G  97% /
tmpfs            64M     0   64M   0% /dev
devtmpfs        3.4G     0  3.4G   0% /dev/tty
shm              63M     0   63M   0% /dev/shm
tmpfs           694M   68K  694M   1% /etc/hosts
/dev/root        84G   80G  3.3G  97% /usr/share/zoneinfo/Etc/UTC
```

</details>

It fills up completely. So the installation fails when running

```
[...]
4.tar: no space left on device
 * docker-archive: writing blob: adding layer with blob "sha256:3a73bd939a78366c5e59ef8d4ce7b6823976fe6298322f4e9c72119621e8c07e": creating layer with ID "ab777ea45e09096310c1ae52618604fbbf2fe0f34a7d98bd02306ace69e4e66e": no space left on device
 * dir: open /var/tmp/podman2292154369/manifest.json: not a directory
ERROR Failed to install the container image

Converting document to safe PDF
> /usr/bin/podman run --network none -u dangerzone --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -v /tmp/tmpyvxpvs5k/unsafe/input_file:/tmp/input_file:Z -v /tmp/tmpyvxpvs5k/pixels:/tmp/dangerzone:Z -e ENABLE_TIMEOUTS=1 dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
ERROR Invalid JSON returned from container:

         Trying to pull dangerzone.rocks/dangerzone:latest...

ERROR [doc Pvmffo] -1% Invalid JSON returned from container:

         Trying to pull dangerzone.rocks/dangerzone:latest...

ERROR Invalid JSON returned from container:

         Error: initializing source docker://dangerzone.rocks/dangerzone:latest: pinging container registry dangerzone.rocks: invalid status code from registry 404 (Not Found)

ERROR [doc Pvmffo] -1% Invalid JSON returned from container:

         Error: initializing source docker://dangerzone.rocks/dangerzone:latest: pinging container registry dangerzone.rocks: invalid status code from registry 404 (Not Found)

ERROR documents-to-pixels failed

Failed to convert document(s)
/home/user/dangerzone/tests/test_docs/sample-pdf.pdf
Traceback (most recent call last):
  File "/home/runner/work/dangerzone/dangerzone/./dev_scripts/env.py", line 606, in <module>
    sys.exit(main())
  File "/home/runner/work/dangerzone/dangerzone/./dev_scripts/env.py", line 602, in main
    return args.func(args)
  File "/home/runner/work/dangerzone/dangerzone/./dev_scripts/env.py", line 494, in env_run
    env.run(args.command, gui=args.gui, user=args.user, dry=args.dry, dev=args.dev)
  File "/home/runner/work/dangerzone/dangerzone/./dev_scripts/env.py", line 404, in run
    self.runtime_run(*run_cmd)
  File "/home/runner/work/dangerzone/dangerzone/./dev_scripts/env.py", line 297, in runtime_run
    subprocess.run(self.runtime_cmd + list(args), check=True)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'run', '--rm', '-it', '-v', '/etc/localtime:/etc/localtime:ro', '--security-opt', 'seccomp=unconfined', '--privileged', '--uidmap', '1000:0:1', '--uidmap', '0:1:1000', '--uidmap', '1001:1001:64536', '--gidmap', '1000:0:1', '--gidmap', '0:1:1000', '--gidmap', '1001:1001:64536', '-v', '/home/runner/work/dangerzone/dangerzone:/home/user/dangerzone', '-v', '/home/runner/work/dangerzone/dangerzone/dev_scripts/envs/debian/trixie/state/containers:/home/user/.local/share/containers', '-v', '/home/runner/work/dangerzone/dangerzone/dev_scripts/envs/debian/trixie/state/.bash_history:/home/user/.bash_history', '-u', 'user', '--hostname', 'dangerzone', 'dangerzone.rocks/debian:trixie', 'dangerzone-cli', 'dangerzone/tests/test_docs/sample-pdf.pdf']' returned non-zero exit status 1.

```

**Comment by deeplow** [comment]
The trixie image is already there taking some space:
```
runner@fv-az1233-442:~/work/dangerzone/dangerzone$ podman images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
dangerzone.rocks/debian   trixie      321d2aa78375  3 hours ago  2.99 GB
docker.io/library/debian  trixie      af227ed3112f  3 weeks ago  120 MB
```

So the two combined are probably exceeding.

**Comment by deeplow** [comment]
In the VM I did `sudo rm ./dev_scripts/envs/debian -r` and I was able to get 16GB of disk:

```
runner@fv-az1233-442:~/work/dangerzone/dangerzone$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   68G   16G  82% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   20K  694M   1% /run/user/1001
```


Then I built the trixie development container with `./dev_scripts/env.py  --distro debian --version trixie build`, loosing about 1G. So we supposedly have 15G left.

However, when I run `dangerzone-cli` and monitor the space within the container (but I guess it could be outside), it goes from 15G down to 0G.

So the question is: **why is the dangerzone image installation taking so much space?**


---

On my system the image tree is as follows

```
Image ID: d1ab18bdcb9f
Tags:     [dangerzone.rocks/dangerzone:latest]
Size:     1.941GB
Image Layers
├── ID: 78a822fe2a2d Size: 7.622MB Top Layer of: [docker.io/library/alpine:latest]
├── ID: 03e6c1f1a464 Size: 868.2MB
├── ID: 5f565220a32f Size: 1.065GB
├── ID: e96973437f5e Size:  5.12kB
├── ID: e43ec674c598 Size:  7.68kB
├── ID: ade78490b76a Size:  89.6kB
└── ID: 8196861adf31 Size: 18.43kB Top Layer of: [dangerzone.rocks/dangerzone:latest]
````

and uncompressed the image is around 2.1G. This is inconsistent with he results of filling up 15G of space.

**Comment by apyrgio** [comment]
Suggestion: Could it be that the created OCI image in the `build-deb` step is actually corrupted (due to low disk space), and the loading it in Podman hits a bug where it fills the whole disk space?

**Comment by apyrgio** [comment]
Turns out that the CI runners were legitimately running out of disk space. The underlying reason is that in some of the end-user environments (those created by `./dev_scripts/env.py ... build-dev`), Podman somehow used the `vfs` storage driver, instead of the more storage-efficient `overlay` one.

The `vfs` storage driver basically copies each layer under a different directory, and then adds the changed files on top. This is very space-intensive, and would bite us at some point.

To fix this, we must configure Podman within the Dangerzone environment to use the `overlay` storage driver, by providing the following `~/.config/containers/storage.conf` file:

```ini
[storage]
driver = "overlay"
```

_Note: Given that the `overlay` storage driver is usually the default, it's weird that Podman uses `vfs`, without any apparent warning. If we get bitten by this again, we should probably check if certain Podman versions have a regression._
