### ISSUE TITLE
env.py: Dangerzone fails to run via env.py

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#673]
I wanted to test dangerzone on ubuntu 20.04 but unfortunately I failed to run podman under podman with the following error:

```python
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
Traceback (most recent call last):
  File "./dev_scripts/dangerzone-cli", line 13, in <module>
    dangerzone.main()
  File "/root/.cache/pypoetry/virtualenvs/dangerzone-hQU0mwlP-py3.8/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/dangerzone-hQU0mwlP-py3.8/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/dangerzone-hQU0mwlP-py3.8/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/dangerzone-hQU0mwlP-py3.8/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/dangerzone/dangerzone/errors.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/user/dangerzone/dangerzone/cli.py", line 96, in cli_main
    dangerzone.isolation_provider.install()
  File "/home/user/dangerzone/dangerzone/isolation_provider/container.py", line 64, in install
    if Container.is_container_installed():
  File "/home/user/dangerzone/dangerzone/isolation_provider/container.py", line 106, in is_container_installed
    found_image_id = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/podman', 'image', 'list', '--format', '{{.ID}}', 'dangerzone.rocks/dangerzone']' returned non-zero exit status 125.
```

**Comment by apyrgio** [comment]
Note that Ubuntu Focal will be deprecated soon by us (#965), so I don't think we need to dig deeper here. I can run tests on Ubuntu Focal successfully and so does our GHA, so that should do for now.
