### ISSUE TITLE
Failing to run build-rpm.py (ValueError: Globs did not match any module: dangerzone)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#675]
At the moment in my development environment, I'm failing to build the RPM. This issue was hapenning on my Qubes system and I didn't invest time figuring it out, since it was still buildable via our `env.py` script. However, now the same issue affects that build environment as well.

Here's the end of the build log:

```
++ wc -l /home/user/dangerzone/install/linux/rpm-build/BUILD/dangerzone-0.5.1-1.fc38.x86_64-pyproject-ghost-distinfo
++ cut -f1 '-d '
+ lines=1
+ '[' 1 -ne 1 ']'
+ RPM_PERCENTAGES_COUNT=8
+ /usr/bin/python3 /usr/lib/rpm/redhat/pyproject_save_files.py --output-files /home/user/dangerzone/install/linux/rpm-build/BUILD/dangerzone-0.5.1-1.fc38.x86_64-pyproject-files --output-modules /home/user/dangerzone/install/linux/rpm-build/BUILD/dangerzone-0.5.1-1.fc38.x86_64-pyproject-modules --buildroot /home/user/dangerzone/install/linux/rpm-build/BUILDROOT/dangerzone-0.5.1-1.fc38.x86_64 --sitelib /usr/lib/python3.11/site-packages --sitearch /usr/lib64/python3.11/site-packages --python-version 3.11 --pyproject-record /home/user/dangerzone/install/linux/rpm-build/BUILD/dangerzone-0.5.1-1.fc38.x86_64-pyproject-record --prefix /usr dangerzone
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_save_files.py", line 800, in <module>
    main(cli_args)
  File "/usr/lib/rpm/redhat/pyproject_save_files.py", line 746, in main
    file_section, module_names = pyproject_save_files_and_modules(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rpm/redhat/pyproject_save_files.py", line 727, in pyproject_save_files_and_modules
    generate_file_list(paths_dict, globs, include_auto)
  File "/usr/lib/rpm/redhat/pyproject_save_files.py", line 534, in generate_file_list
    raise ValueError(f"Globs did not match any module: {missed_text}")
ValueError: Globs did not match any module: dangerzone
error: Bad exit status from /var/tmp/rpm-tmp.sI8OR5 (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.sI8OR5 (%install)
Traceback (most recent call last):
  File "/home/user/dangerzone/./install/linux/build-rpm.py", line 115, in <module>
    main()
  File "/home/user/dangerzone/./install/linux/build-rpm.py", line 111, in main
    build(args.qubes)
  File "/home/user/dangerzone/./install/linux/build-rpm.py", line 97, in build
    subprocess.run(cmd, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rpmbuild', '-v', '--define', '_topdir /home/user/dangerzone/install/linux/rpm-build', '-ba', '--nodebuginfo', '/home/user/dangerzone/install/linux/rpm-build/SPECS/dangerzone.spec']' returned non-zero exit status 1.
```

**Comment by apyrgio** [comment]
Sigh, I send a PR (#679) but I didn't realize we had an issue. Closing it in favor of #678, which offers a bit more context on the reason why our RPM builds fail.
